### ISSUE TITLE
Time Log Formatting

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jcaughlin/StudentAchieve#2]
I think this isn't rendering correctly due to an extra "column". Try changing 
|------|------|------|-------|------| 
to 
|------|------|------|-------|

**Comment by jcaughlin** [comment]
I was using MacDown. I am guessing it ignores what it can in order to render. I wish the was a form or another way to track time as I forget the extra step. I have been playing around with this plugin which is supposed to track time spent in Intellij


# TIME LOG-JS CAUGHLIN



|Week| Date | Task | Hours |
|------|------|------|-------|
|1|1/14/17| Development Environment Set Up| 1| 
|1|1/14/17| Development Environment Set Up| 1| 
|2|1/19/17| Database Design|3|
|2|1/20/17| Week 1 Excercise|3|
|3|1/20/17| POJO Sketching|2|
|3|1/28/17| Work on JUNIT Excercise| 5| 
|3|2/2/17| Wireframes & Screen Design|4|
|4|2/4/17 | Project Plan Student Repository|2|
|4|2/9/17|Individual Project Entities |3|
|4|2/10/17|3 & 4|3|
|5|2/14/17|Individual Project Servlets|2|

**Comment by pawaitemadisoncollege** [comment]
You can use anything you like to track your time, just as long as I can see it anytime - that could mean another file format, or a google doc, or...
